### PR TITLE
appveyor: disable the cache

### PR DESCRIPTION
**Pull request by japaric**
it seems that we are hitting the cache size limit

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 77e9140 has been approved by `japaric`

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 6ac3c01 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 6ac3c01ea28c5d767f634ae8c4ce675bd5746e30 with merge c613a43a5b2353a46951daf77ceecda8c77203bb...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/svd2rust/build/1.0.133), [status-travis](https://travis-ci.org/japaric/svd2rust/builds/284859037?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing c613a43a5b2353a46951daf77ceecda8c77203bb to master...

**Pull request merged**
