### PR TITLE
Avoid generating code for reserved fields and enumerated values.

### LINKED ISSUE #87: Registers with multiple reserved fields causes duplicate definitions
Running the tool on [this svd file](https://gist.github.com/simonvandel/6a67b7893f89482b8be2b7ac75a661b6) generates code that does not compile.

The error message reads:
```
error[E0201]: duplicate definitions with name `reserved`:
      --> src/lib.rs:156931:13
       |
156881 | /             pub fn reserved(&self) -> ReservedR {
156882 | |                 let bits = {
156883 | |                     const MASK: u8 = 1;
156884 | |                     const OFFSET: u8 = 0;
...      |
156887 | |                 ReservedR { bits }
156888 | |             }
       | |_____________- previous definition of `reserved` here
...
156931 | /             pub fn reserved(&self) -> ReservedR {
156932 | |                 let bits = {
156933 | |                     const MASK: u32 = 134217727;
156934 | |                     const OFFSET: u8 = 5;
...      |
156937 | |                 ReservedR { bits }
156938 | |             }
       | |_____________^ duplicate definition

```

This happens as a lot of registers in the svd file has multiple reserved fields.

I see two different solutions to this problem:
1. Edit the SVD file, appending a unique string to each conflicting RESERVED field.
2. Change svd2rust, by special casing registers  with multiple reserved fields such that unique field names are generated. i.e. RESERVED1, RESERVED2

What do you think?

### PR DESCRIPTION
**Pull request by simonvandel**
This is my attempt to fix #87.

Code is still being generated for reserved, but this reduces most cases.

### CODE REVIEW

**Comment by japaric** [comment]
Thanks, @simonvandel!

@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 2c34e26 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 2c34e26 with merge 2c34e26...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/svd2rust/build/1.0.72), [status-travis](https://travis-ci.org/japaric/svd2rust/builds/232657684?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 2c34e26126ec9f703e08b6e8d251fa178d086a1a to master...

**Pull request merged**
