### PR TITLE
Switch to usage of quote+syn rather than aster+quasi_quote.

### PR DESCRIPTION
**Pull request by brandonedens**

### CODE REVIEW

**Comment by japaric** [comment]
Truly awesome @brandonedens!

@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 3c65375 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 3c65375 with merge 3c65375...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/svd2rust/builds/167408861)
Approved by: japaric
Pushing 3c653754b9c2d978a2928af3083137ceb8378604 to master...

**Pull request merged**
