### PR TITLE
`.modify()`: give access to readable bits of the register

### LINKED ISSUE #3: the `modify` method should probably expose the readable bits of the register
Possible implementation:

``` rust
impl Cr1 {
    pub fn modify<F>(&mut self, f: F)
        where F: FnOnce(&Cr1R, &mut Cr1W) -> &mut Cr1W
    {
        let bits = self.register.read();
        let mut w = Cr1W { bits: bits };
        let r = Cr1R { bits: bits }
        f(&r, &mut w);
        self.register.write(rw.bits);
    }
}
```

Usage:

``` rust
// Toggle the SADD0 bit
i2c1.cr1.modify(|r, w| w.sadd0(!r.sadd0()));
```

### PR DESCRIPTION
**Pull request by japaric**
closes #3

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 5f9ef5d with merge 5f9ef5d...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/svd2rust/builds/166245889)
State: approved= try=True

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 83175e5 has been approved by `japaric`

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 1536f4e has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 1536f4e with merge d48e8ec...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/svd2rust/builds/166259133)
Approved by: japaric
Pushing d48e8ec25763cc03b91c653579d0bbeeb732f079 to master...

**Pull request merged**
