### PR TITLE
Normalize SVD names to upper case where they were to pascal case

### LINKED ISSUE #76: Name mangling is lossy around numbers
E.g. both `ADC_SPC_PHASE_22_5` and `ADC_SPC_PHASE_225` converge to `AdcSpcPhase225`.

### PR DESCRIPTION
**Pull request by whitequark**
Fixes #76.

Depends on https://github.com/calebmer/inflections/pull/2.

### CODE REVIEW

**Comment by whitequark** [comment]
So... yes, I understand that right now, I am being *that person* who asks to change style conventions. However, I feel that there are a few factors in the favor of this change:
  * The current behavior is clearly broken, and cannot be fixed and still be fully compliant with Rust's naming conventions for struct names (as described in #76);
  * Normalizing peripheral and register names to PascalCase is unprecedented in embedded development;
  * Normalizing peripheral and register names to PascalCase means there is no trivial mapping from the datasheet names to API names (unlike with snake_case, where it is a simple substitution);
  * Virtually all peripheral and register, and most enumeration names are complex abbreviations, which means that normalizing them to PascalCase *always* decreases readability;
  * svd2rust already has precedent for this: 7b585ac8.

And I suppose if this PR is merged, then the corresponding change should be done to `cortex-m` as well.

**Comment by japaric** [comment]
> Normalizing peripheral and register names to PascalCase is unprecedented in embedded development;

(Rust is unprecedent in embedded development :-). And C just uses integers to represent registers instead of newtypes so C code doesn't have to deal with this.)

I kinda agree with the rationale outlined here but I'd like to take my time in assessing the breakage this will cause to dependent crates.

**Comment by whitequark** [comment]
> Rust is unprecedent in embedded development :-)

I think you'll find the Habit bitdata types (see [Habit report p.40](http://hasp.cs.pdx.edu/habit-report-Nov2010.pdf)) quite familiar, actually...

**Comment by whitequark** [comment]
@japaric From your latest post:

> When using the RTFM framework you have to declare all the peripherals you are going to use in this macro. **Both the name of the peripheral (for example: GPIOE) and its type (for example: Gpioe) must match the device crate**, stm32f30x in this case, definitions.

Seems like this PR would make that a bit cleaner :)

**Comment by japaric** [comment]
Bascially r+ but we have to wait for inflections PR to be merged. Turns out this change won't break cortex-m-rtfm because the register_block field in the peripherals! macro can be made optional. (see japaric/cortex-m-rtfm#28)

**Comment by japaric** [comment]
This is waiting on a new release of the inflections crate.

**Comment by japaric** [comment]
Thank you @whitequark!

@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 601cc70 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 601cc70 with merge ae89a86...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/svd2rust/build/1.0.79), [status-travis](https://travis-ci.org/japaric/svd2rust/builds/239448743?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing ae89a86dd5d798ea502508de47da5143dafd8cbe to master...

**Pull request merged**
