### PR TITLE
tweak interrupt handler signature, update CI

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 28a5119 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 28a5119 with merge 28a5119...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 2bc1835 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 2bc1835 with merge 2bc1835...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/svd2rust/builds/210192174)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit c5d6757 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit c5d6757 with merge c5d6757...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/svd2rust/build/1.0.46), [status-travis](https://travis-ci.org/japaric/svd2rust/builds/210193290)
Approved by: japaric
Pushing c5d67574c06c619eb7d4150c8a9ea67987017bd2 to master...

**Pull request merged**
