### PR TITLE
sprinkle #[repr(C)] everywhere

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit a6e44df has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit a6e44df with merge a6e44df...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/svd2rust/builds/166326043)
Approved by: japaric
Pushing a6e44dfe51763b08a7f426a8c6e724ea0cbd7536 to master...

**Pull request merged**
