### PR TITLE
don't expose reserved fields (bit ranges actually)

### LINKED ISSUE #42: Function name collision avoidance
The .svd file I use has multiple **reserved** bit ranges per register, leading to duplicate `fn reserved()` in struct impls. If that happens, those fields could either be omitted or get mangled into `reserved1`, `reserved2`, ...

### PR DESCRIPTION
**Pull request by japaric**
fixes #42

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit afc5fb2 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit afc5fb2 with merge afc5fb2...

**Comment by japaric** [comment]
cc @astro

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/svd2rust/build/1.0.27), [status-travis](https://travis-ci.org/japaric/svd2rust/builds/186370043)
Approved by: japaric
Pushing afc5fb25a14ae8c5ebba4ddd41e7b51991c26d61 to master...

**Comment by astro** [comment]
\o/

Thank you!

**Pull request merged**
