### PR TITLE
mark interrupts tokens as !Send

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 3ea5744 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 3ea5744 with merge 3ea5744...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/svd2rust/build/1.0.70), [status-travis](https://travis-ci.org/japaric/svd2rust/builds/230060379?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 3ea574478f617ed887a93eda05fb2a74a66eb817 to master...

**Pull request merged**
