### PR TITLE
Handle missing dimIndex on registers

### LINKED ISSUE #150: SVD Registers with no dimIndex
According to the CMSIS standard:
https://www.keil.com/pack/doc/CMSIS/SVD/html/elem_special.html 

dimElementGroups with "[%s]" in their name are not suppose to use the dimIndex tag. I have an SVD that currently is doing this but getting an error due to the tag missing. The SVD file is loaded in #146 but will only get that far if my PR in japaric/svd#40 is used.

Requesting the the dimIndex missing be allowed if name contains [%s]

### PR DESCRIPTION
**Pull request by kevinmehall**
This supersedes @lucasbrendel's similar PR #153 and fixes #150.

Per the [SVD spec](http://arm-software.github.io/CMSIS_5/SVD/html/elem_special.html#dimElementGroup_gr), dimIndex is not required:

> By default, \<dimIndex\> is a value starting with 0.
> Remark: Do not define \<dimIndex\> when using the placeholder [%s] in \<name\> or \<displayName\>.

I interpret this as the element being optional with "%s" and not allowed with "[%s]" (this change does not reject the latter). Atmel SAMD21 SVDs use "%s" with no dimIndex for 0-indexed arrays.

This also tests that dimIndex is sequential and numeric in a single pass without allocating temporary vectors, and fixes the typo adresses -> addresses.

### CODE REVIEW

**Comment by jamesmunns** [comment]
Not sure how I missed this, but this PR also addresses the issues I had mentioned in https://github.com/japaric/svd2rust/pull/177.

:+1: from me!

**Comment by jamesmunns** [comment]
@therealprof you may want to test your svds with this branch.

**Comment by therealprof** [comment]
@jamesmunns For the ATSAMD the result is pretty much the same (as far as I can tell from memory it's indentical) as with your PR. The result in this particular case is still broken but I blame Atmel here.

**Comment by kevinmehall** [comment]
@therealprof Yeah, the SAMD SVDs will still need some more features implemented including `derivedFrom` on registers, register clusters, and building unions for registers with duplicate addresses. None of which is actually in violation of the SVD spec as far as I've seen, but yes, they definitely could have done it more elegantly.

**Comment by japaric** [comment]
@homunkulus r+

**Comment by japaric** [comment]
bors retry

**Comment by japaric** [comment]
bors-ng doesn't seem to have a retry command implemented, then ...

bors r+

**Comment by japaric** [comment]
[All tests passed](https://travis-ci.org/japaric/svd2rust/builds/345753607). Merging manually.

**Pull request merged**
