### PR TITLE
Weak aliases should only point to defined symbols.

### PR DESCRIPTION
**Pull request by pftbest**
Add an extra function as a possible solution for
https://github.com/japaric/cortex-m-rtfm/issues/39

### CODE REVIEW

**Comment by japaric** [comment]
Thanks @pftbest 

@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit f0127b7 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit f0127b7 with merge f0127b7...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/svd2rust/build/1.0.117), [status-travis](https://travis-ci.org/japaric/svd2rust/builds/260029292?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing f0127b7220b0270219ea10aa6373ab71dc20ea4b to master...

**Pull request merged**
