### PR TITLE
support registers without `fields`

### PR DESCRIPTION
**Pull request by japaric**
cc @istankovic

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 4522caa has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 4522caa with merge 4522caa...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/svd2rust/build/1.0.25), [status-travis](https://travis-ci.org/japaric/svd2rust/builds/185839799)
Approved by: japaric
Pushing 4522caa826e706931da49f0432fea6665eb8922f to master...

**Pull request merged**
