### PR TITLE
add CI

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 36a4fce has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 36a4fce with merge 36a4fce...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 89c716f has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 89c716f with merge 89c716f...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/svd2rust/builds/166241116)
Approved by: japaric
Pushing 89c716f81844b0b83651a760001e294de9494917 to master...

**Pull request merged**
