### PR TITLE
fix code generated from enumeratedValues.derivedFrom

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 76e3dd6 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 76e3dd6 with merge 76e3dd6...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/svd2rust/build/1.0.52), [status-travis](https://travis-ci.org/japaric/svd2rust/builds/217557284)
Approved by: japaric
Pushing 76e3dd64df518c3230e9482dac4a69286b2e8a2e to master...

**Pull request merged**
