### PR TITLE
.travis: remove webhooks

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit b456335 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit b456335 with merge b456335...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/svd2rust/build/1.0.7), [status-travis](https://travis-ci.org/japaric/svd2rust/builds/174107414)
Approved by: japaric
Pushing b4563351a9e1c53b6d5e57ad674c9dc5cc94a0a4 to master...

**Pull request merged**
