### PR TITLE
CI: use the trust template

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit d183d83 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit d183d83 with merge d183d83...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/svd2rust/builds/190010655)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 5834ed1 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 5834ed1 with merge 5834ed1...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/svd2rust/builds/190013516)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 43490a9 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 43490a9 with merge 43490a9...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/svd2rust/builds/190018651)

**Comment by japaric** [comment]
@homunkulus retry

**Comment by homunkulus** [comment]
:hourglass: Testing commit 43490a9 with merge 43490a9...

**Comment by japaric** [comment]
@homunkulus retry

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit a6a3e76 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit a6a3e76 with merge a6a3e76...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/svd2rust/builds/190021599)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit d7b0f03 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit d7b0f03 with merge d7b0f03...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/svd2rust/build/1.0.35), [status-travis](https://travis-ci.org/japaric/svd2rust/builds/190036035)
Approved by: japaric
Pushing d7b0f03a0eb7f28a6e832d31ff37d0779ac83922 to master...

**Pull request merged**
