### PR TITLE
add tests for the msp430 and none targets

### LINKED ISSUE #161: add non-cortex-m code generation tests
for msp430 and the "none" targets

### PR DESCRIPTION
**Pull request by japaric**
fix codegen for the msp430 target

closes #161

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 7d3155e has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 7d3155ea3d930fbd598a6f855fee6f3178ea70a9 with merge 92067f7fd50dab834eb1c6152143128a5932be45...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/svd2rust/build/1.0.140), [status-travis](https://travis-ci.org/japaric/svd2rust/builds/320783006?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 92067f7fd50dab834eb1c6152143128a5932be45 to master...

**Pull request merged**
