### PR TITLE
Svd clusters

### PR DESCRIPTION
**Pull request by brandonedens**
Add support for generating rust software to support the <cluster> tag.

### CODE REVIEW

**Comment by Emilgardis** [comment]
@brandonedens are you still working on this?

**Comment by Emilgardis** [comment]
ping @brandonedens

**Comment by jamesmunns** [comment]
@Emilgardis I am working on fixing the merge conflicts for this. I will open it up as a separate PR when it is ready (hopefully soon).

**Comment by jamesmunns** [comment]
WIP here: https://github.com/jamesmunns/svd2rust/tree/james-cluster - merge is probably 80ish% done, still need to clean up a couple things.

**Comment by brandonedens** [comment]
Closed in favor of James work.

**Pull request closed without merging**
