### PR TITLE
adapt to incoming changes in cortex-m and cortex-m-rt

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 5e2da93 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 5e2da93 with merge 5e2da93...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/svd2rust/build/1.0.104), [status-travis](https://travis-ci.org/japaric/svd2rust/builds/250126476?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 5e2da93e941b0557fd7738aca9c30828f80a07f0 to master...

**Pull request merged**
