### PR TITLE
switch back to a current nightly

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 71f9562 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 71f9562 with merge 71f9562...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/svd2rust/build/1.0.80), [status-travis](https://travis-ci.org/japaric/svd2rust/builds/239450654?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 71f95627f94c885648ba93df5b5c357d465f8302 to master...

**Pull request merged**
