### PR TITLE
add git commit/date info to the output of -V

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 9641d2a has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 9641d2a with merge 9641d2a...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/svd2rust/build/1.0.4), [status-travis](https://travis-ci.org/japaric/svd2rust/builds/167829317)
Approved by: japaric
Pushing 9641d2a7f458e68838a99d3ea056532bc8166e32 to master...

**Pull request merged**
