### PR TITLE
[MSP430] User defined interrupt handlers should have correct CC.

### PR DESCRIPTION
**Pull request by pftbest**

### CODE REVIEW

**Comment by japaric** [comment]
Thanks @pftbest.

@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 7e34184 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 7e34184 with merge 7e34184...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/svd2rust/builds/252542810?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
Failure due to time limit but all tests passed.

**Pull request merged**
