### PR TITLE
full test suite

### PR DESCRIPTION
**Pull request by japaric**
let's see if this times out

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 8e62276 with merge 8e62276...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/svd2rust/builds/239473042?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 027e79d with merge 027e79d...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/svd2rust/builds/239621030?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 6832a4a with merge 6832a4a...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/svd2rust/builds/239625467?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit c133169 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit c133169 with merge c133169...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/svd2rust/builds/239662011?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 4acd609 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 4acd609 with merge 4acd609...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/svd2rust/builds/239695405?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit f993703 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit f993703 with merge f993703...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/svd2rust/builds/239706513?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit f5a34a4 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit f5a34a4 with merge f5a34a4...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/svd2rust/builds/239770635?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit a8f19df has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit a8f19df with merge a8f19df...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/svd2rust/build/1.0.95), [status-travis](https://travis-ci.org/japaric/svd2rust/builds/239783627?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing a8f19dffd87e167315c036648cd4c99909bda43a to master...

**Pull request merged**
