### PR TITLE
Replace #[inline(always)] by #[inline] due to the later being conside…

### PR DESCRIPTION
**Pull request by therealprof**
…red harmful

Signed-off-by: Daniel Egger <daniel@eggers-club.de>

### CODE REVIEW

**Comment by japaric** [comment]
("being considered harmful" is not a very descriptive commit message / PR title, IMO.)

For posteriority, could you please add a comment (or a link) with the rationale about the change to this PR?

@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 73cd404 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 73cd404 with merge 895722b...

**Comment by therealprof** [comment]
Well, according to https://rust-lang-nursery.github.io/rust-clippy/master/index.html#inline_always it is considered harmful: It increases compile time and may increase size as well as decrease performance. I'm afraid I can't come up with a better label than "considered harmful".

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/svd2rust/build/1.0.123), [status-travis](https://travis-ci.org/japaric/svd2rust/builds/277572867?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 895722b6ec85cd7dae5d37eb9622a3e665ba6a27 to master...

**Pull request merged**
