### PR TITLE
Peripherals as scoped singletons

### PR DESCRIPTION
**Pull request by japaric**
See this RFC for details: japaric/svd2rust#157

With this change device crates will need to depend on a version of the cortex-m crate that includes japaric/cortex-m#65

### TODO

- [x] accept the RFC
- [ ] ~~Check that non cortex-m targets still work~~ postponed
- [x] decide on better names for `Peripherals::{all,_all}`

### CODE REVIEW

**Comment by japaric** [comment]
Regarding names, how about `Peripherals::take` for the safe `-> Option<Self>` version since it resembles the `Option.take` method. And maybe ... `Peripherals::steal` for the unsafe version, since it's unchecked? Another option for the latter could be `take_unchecked` or something with "unchecked" word in it.

**Comment by japaric** [comment]
> Regarding names, ...

I'm going ahead with `take` and `steal`.

> Check that non cortex-m targets still work

I'm going to defer this until right before the actual release

@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit e114878 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit e114878c9a243821789c6ef74167bc565100caa5 with merge a2a9b72cc5d7c2673949e360392ad3f98a99a076...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 56cd979 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 56cd9797cf65da03ff565e4a110b9e0e9009412d with merge 5b0bf79fc576ef485ed57fcbc17e56025afd4738...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/svd2rust/builds/313914141?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 9c2ec7b has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 9c2ec7b18560b5d72f3c48eb4c7d895c9fcbb984 with merge 26c2ef9cd297670f98db58f1dc6f5dce692f1822...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 3b27815 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 3b2781554f02724bbbbf5c29cd40970b2cd125fc with merge 227a0b1864fabb6b9c58f974b465355e8bd14b7e...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/svd2rust/build/1.0.139), [status-travis](https://travis-ci.org/japaric/svd2rust/builds/313933446?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 227a0b1864fabb6b9c58f974b465355e8bd14b7e to master...

**Comment by hannobraun** [comment]
> > Regarding names, ...
> 
> I'm going ahead with `take` and `steal`.

I like those! Short and to the point!

**Pull request merged**
