### PR TITLE
expose bits

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 7457cf3 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 7457cf3 with merge 7457cf3...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/svd2rust/build/1.0.29), [status-travis](https://travis-ci.org/japaric/svd2rust/builds/187918720)
Approved by: japaric
Pushing 7457cf376afc24f9fd3c0b3a55e4a9ee0d674efe to master...

**Pull request merged**
