### PR TITLE
`.write()`: change signature to take a closure that modifies the reset

### LINKED ISSUE #2: ideally the `write` method shouldn't require importing a `struct`

### PR DESCRIPTION
**Pull request by japaric**
value

closes #2

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 028a95b with merge 028a95b...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/svd2rust/builds/166249056)
State: approved= try=True

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 83175e5 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 83175e5 with merge 83175e5...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/svd2rust/builds/166257832)
Approved by: japaric
Pushing 83175e5a041d7c15055aea1d1a69e281a1d146d3 to master...

**Pull request merged**
