### PR TITLE
add support for register arrays

### PR DESCRIPTION
**Pull request by japaric**
cc @istankovic

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus try

svd-parser needs a new release before this lands

**Comment by homunkulus** [comment]
:hourglass: Trying commit db5f83d with merge db5f83d...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/svd2rust/build/1.0.23), [status-travis](https://travis-ci.org/japaric/svd2rust/builds/185646595)
State: approved= try=True

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 57e9e72 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 57e9e72 with merge 57e9e72...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/svd2rust/build/1.0.24), [status-travis](https://travis-ci.org/japaric/svd2rust/builds/185810542)
Approved by: japaric
Pushing 57e9e7269cb9d5ada734ddf2325a41846eeeaed3 to master...

**Pull request merged**
