### PR TITLE
Register arrays, registers without fields...

### PR DESCRIPTION
**Pull request by istankovic**

### CODE REVIEW

**Comment by japaric** [comment]
Thanks, @istankovic!

@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 220926f has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 220926f with merge 220926f...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-appveyor](https://ci.appveyor.com/project/japaric/svd2rust/build/1.0.20)

**Comment by homunkulus** [comment]
:umbrella: The latest upstream changes (presumably e94b369) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by japaric** [comment]
I just ran into the need for this so I'll probably take a stab at it today.

**Comment by astro** [comment]
Works for me.

In the .svd for the LPC43XX I encountered `<name>B[%s]</name>` which I renamed with an additional `.replace("[%s]", "")` in `register_basename()`.

**Comment by istankovic** [comment]
@japaric Unfortunately, I did not complete the work here simply due to lack of time.  If you can add support for register arrays, it will be greatly appreciated.  :-)

**Comment by japaric** [comment]
Closing in favor of #43

**Pull request closed without merging**
