### PR TITLE
Fix duplicated exception handlers.

### PR DESCRIPTION
**Pull request by pftbest**
A workaround for https://github.com/japaric/cortex-m/issues/19

### CODE REVIEW

**Comment by japaric** [comment]
I'm hitting LLVM assertions when using this with the Cortex-M target:

``` rust
#![no_std]

#[macro_use(interrupt)]
extern crate stm32f103xx;

fn main() {}

interrupt!(TIM2, tim2);

fn tim2() {}
```

``` console
$ tail Cargo.toml
[profile.release]
debug = true
lto = true

$ xargo build --release
rustc: /checkout/src/llvm/lib/MC/MCStreamer.cpp:294: virtual void llvm::MCStreamer::EmitLabel(llvm::MCSymbol*): Assertion `!Symbol->isVariable() && "Cannot emit a variable symbol!"' failed.
```

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit f6aedfa has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit f6aedfa with merge f6aedfa...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-appveyor](https://ci.appveyor.com/project/japaric/svd2rust/build/1.0.114)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit b84f13a has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit b84f13a with merge b84f13a...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/svd2rust/build/1.0.115), [status-travis](https://travis-ci.org/japaric/svd2rust/builds/256275276?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing b84f13af6f4e8c743909b6d4ca1a2d91fdae7a26 to master...

**Pull request merged**
