### PR TITLE
Sanitize register's name

### PR DESCRIPTION
**Pull request by lexxvir**
It's successor for https://github.com/japaric/svd2rust/pull/29, sanitize register's name too.

### CODE REVIEW

**Comment by japaric** [comment]
Makes sense. Thanks!

@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 79aa408 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 79aa408 with merge 79aa408...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/svd2rust/build/1.0.13), [status-travis](https://travis-ci.org/japaric/svd2rust/builds/178308605)
Approved by: japaric
Pushing 79aa408df686a969565c5520c11db6f382378716 to master...

**Pull request merged**
