### PR TITLE
indent police

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 64c833f has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 64c833f with merge 64c833f...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/svd2rust/builds/167418124)
Approved by: japaric
Pushing 64c833f05ee57007271c8d7adcdaa0867982909f to master...

**Pull request merged**
