### PR TITLE
move documentation to src/lib.rs

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 0e9cd60 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 0e9cd60 with merge 0e9cd60...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit d5726a8 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit d5726a8 with merge d5726a8...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/svd2rust/build/1.0.15), [status-travis](https://travis-ci.org/japaric/svd2rust/builds/179201899)
Approved by: japaric
Pushing d5726a8a195f6225e5816f970d12f78282f5d8bf to master...

**Pull request merged**
