### PR TITLE
v0.12.0

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 73dd3ca has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 73dd3ca3f19e2dc5b153654b0c4bcd0de9a366db with merge 1f9a405748cedd4bd3bba255f9c17215e58fca48...

**Comment by japaric** [comment]
One build timed out but it passed locally so I'm going to merge this manually.

**Comment by japaric** [comment]
> One build timed out 

cf. #166 for details

**Pull request merged**
