### PR TITLE
Do not emit `mod interrupt` if there aren't any defined

### LINKED ISSUE #77: #[deny(unused_imports)] errors out in certain circumstances
With my TM4C129x SVD files I currently get these two errors:
```
error: unused import: `cortex_m::ctxt::Context`
 --> src/lib.rs:9:9
  |
9 |     use cortex_m::ctxt::Context;
  |         ^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: #[deny(unused_imports)] implied by #[deny(warnings)]
error: unused import: `cortex_m::exception`
  --> src/lib.rs:10:9
   |
10 |     use cortex_m::exception;
   |         ^^^^^^^^^^^^^^^^^^^
   |
   = note: #[deny(unused_imports)] implied by #[deny(warnings)]
```
I'm not sure why this happens, perhaps because I don't have any interrupts defined?

### PR DESCRIPTION
**Pull request by whitequark**
Or else the resulting file will not compile.

Fixes #77.

### CODE REVIEW

**Comment by japaric** [comment]
> if there aren't any defined

A microcontroller without interrupts? 😞 

Thanks, @whitequark!

@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit ee35f3e has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit ee35f3e with merge ee35f3e...

**Comment by whitequark** [comment]
> A microcontroller without interrupts?

An SVD file without interrupts, because what I generate the SVD file from doesn't seem to list them (?!). In any case, it helps incremental development.

**Comment by japaric** [comment]
> An SVD file without interrupts

FWIW, @Emilgardis ran into something like that and found the list of interrupts in an assembly file, transformed them into something SVD compatible, pasted them inside some <peripheral> tree and it Just Worked.

**Comment by whitequark** [comment]
I'm sure it can be done somehow (worst case I'll just apply an overlay patch) but so far I'd like to stray as little from the vendor's XML as possible...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/svd2rust/build/1.0.64), [status-travis](https://travis-ci.org/japaric/svd2rust/builds/227243001?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing ee35f3e3aa77308cc65f43c2e6f1d53f2d4222b3 to master...

**Pull request merged**
