### PR TITLE
tweak CI

### PR DESCRIPTION
**Pull request by japaric**
don't re-install rustup
faster checks on stable / beta

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 59a1045 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 59a1045 with merge 59a1045...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/svd2rust/builds/239466096?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit a9bf77e has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit a9bf77e with merge a9bf77e...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/svd2rust/build/1.0.87), [status-travis](https://travis-ci.org/japaric/svd2rust/builds/239468652?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing a9bf77ee7c8e966575ab4c1c2cf3e750f7307820 to master...

**Pull request merged**
