### PR TITLE
generate a different type for each peripheral instance

### LINKED ISSUE #65: [RFC] one type per register block
Right now, when dealing with derived peripherals, svd2rust uses type aliases:

``` rust
pub mod tim2 {
    pub struct RegisterBlock { .. }
}

pub use tim2::RegisterBlock as Tim2;
pub type Tim3 = Tim2;
pub type Tim4 = Tim2;
pub type Tim5 = Tim2;
```

Thus all both the base peripheral and the derived peripherals have the same
type.

I propose we change svd2rust to generate a different type for each peripheral.

``` rust
pub mod tim2 {
    pub struct RegisterBlock { .. }
}

pub struct Tim2 { register_block: tim2::RegisterBlock }
impl Deref for Tim2 { type Target = tim2::RegisterBlock; .. }

pub struct Tim3 { register_block: tim2::RegisterBlock }
impl Deref for Tim3 { type Target = tim2::RegisterBlock; .. }

pub struct Tim4 { register_block: tim2::RegisterBlock }
impl Deref for Tim4 { type Target = tim2::RegisterBlock; .. }

pub struct Tim5 { register_block: tim2::RegisterBlock }
impl Deref for Tim5 { type Target = tim2::RegisterBlock; .. }
```

The rationale is that you may want to have API that works for one peripheral,
e.g. TIM2, but not for the others. You can only enforce that if you have
different types for the peripherals. Another similar use case is APIs that
depend on some specific combinations of peripherals: PWM1 = GPIOA + TIM2, PWM2 =
GPIOB + TIM3, etc.

### PR DESCRIPTION
**Pull request by japaric**
closes #65

barely tested. Seems to work though

### CODE REVIEW

**Comment by japaric** [comment]
As I've heard no complains, have received positive feedback through other channels and I've tested this more thoroughly, I'm going to go ahead and land this.

@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 74f1c3e has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 74f1c3e with merge 74f1c3e...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/svd2rust/build/1.0.50), [status-travis](https://travis-ci.org/japaric/svd2rust/builds/215780520)
Approved by: japaric
Pushing 74f1c3ec9cc7ba912be8e9f005732690008314e0 to master...

**Pull request merged**
