### PR TITLE
Skip registers that overlap

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 5286700 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 5286700 with merge 5286700...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/svd2rust/build/1.0.6), [status-travis](https://travis-ci.org/japaric/svd2rust/builds/169134756)
Approved by: japaric
Pushing 52867003fc64c0b3a8591e8915ee5fa8eda12ae2 to master...

**Pull request merged**
