### PR TITLE
Use far-ranged jumps for DH_TRAMPOLINE

### PR DESCRIPTION
**Pull request by jonas-schievink**
Fixes japaric/cortex-m-rtfm#42

~~Note that this will make all generated crates that target an armv6
device fail to compile unless they add a build script enabling the added
`cfg`.~~ (this is no longer the case, everything should Just Work™)

### CODE REVIEW

**Comment by japaric** [comment]
@jonas-schievink thanks for tackling this.

It just occurred to me that instead of using a #[cfg] and requiring a build script in the device crate we could (a) add a new `--target`, e.g. armv6m, to svd2rust to make it generate this extra function only (so no #[cfg] required) when generating code for an ARMv6 device; or, perhaps even better, (b) we could make svd2rust parse the `<cpu>` information in the SVD file to generate the extra function when dealing with Cortex-M0 and Cortex-M0+ devices. Now, I don't recall if `<cpu>` info is mandatory in SVD files so it may not be available, and it could be the case that it's in the SVD file but it could be incorrect (some SVD files are very low quality).

Thoughts?

**Comment by Samonitari** [comment]
Hi @japaric!
👍  for proposition b): reading the `<cpu>` element.
You also added `const NVIC_PRIO_BITS` generation, and ARM documentation says the whole `<cpu>` is mandatory in case it is used for header generation. svd2rust is as close as it gets...

It reminds me, I should commit somewhere some fixed NXP SVD files, to spare others from the uninspiring labor I had to do.

**Comment by jonas-schievink** [comment]
@japaric Parsing the SVD seems like the best idea, I've pushed a commit doing that.

**Comment by japaric** [comment]
@homunkulus r+

Thanks all for chimming in :-)

**Comment by homunkulus** [comment]
:pushpin: Commit 87ac8d8 has been approved by `japaric`

**Comment by homunkulus** [comment]
:lock: Merge conflict

**Comment by homunkulus** [comment]
:umbrella: The latest upstream changes (presumably bab6f3e) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit a8994ef has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit a8994ef with merge a8994ef...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/svd2rust/build/1.0.120), [status-travis](https://travis-ci.org/japaric/svd2rust/builds/273034875?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing a8994eff5e02fd8f6de54f682c728f77290ef88a to master...

**Pull request merged**
