### PR TITLE
Upgrade Cargo.toml to the latest versions and style

### PR DESCRIPTION
**Pull request by therealprof**
Signed-off-by: Daniel Egger <daniel@eggers-club.de>

### CODE REVIEW

**Comment by japaric** [comment]
Thanks, @therealprof.

@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 5d17f4f has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 5d17f4f with merge 29ee89a...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/svd2rust/build/1.0.124), [status-travis](https://travis-ci.org/japaric/svd2rust/builds/277646097?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 29ee89a2ef3319f2e2c9bc018c0360afeeb663ac to master...

**Pull request merged**
