### PR TITLE
fix generation of interrupt table

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 4a84507 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 4a84507 with merge 4a84507...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/svd2rust/build/1.0.47), [status-travis](https://travis-ci.org/japaric/svd2rust/builds/210289075)
Approved by: japaric
Pushing 4a845075c59e267da52b21e1ffb8e3d8adc9195a to master...

**Pull request merged**
