### PR TITLE
hopefully better error (panic!) messages

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit d38e45e has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit d38e45e with merge d38e45e...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/svd2rust/build/1.0.41), [status-travis](https://travis-ci.org/japaric/svd2rust/builds/206496433)
Approved by: japaric
Pushing d38e45e8a29d3fbc3a7564684426a0e1394ccfb3 to master...

**Pull request merged**
