### PR TITLE
Recognize <writeConstraint> in <register>

### PR DESCRIPTION
**Pull request by whitequark**
This is useful in cases where the entire register is safely writable
and is a uniform collection of bits, e.g. GPIO direction or data
registers.

### CODE REVIEW

**Comment by whitequark** [comment]
Updated to use svd-parser 0.5.1.

**Comment by japaric** [comment]
Good idea. Thanks!

@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit c758eb7 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit c758eb7 with merge c758eb7...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/svd2rust/build/1.0.68), [status-travis](https://travis-ci.org/japaric/svd2rust/builds/227291689?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing c758eb77c4b4ae0c7fb133463c1da755242c0377 to master...

**Pull request merged**
