### PR TITLE
test the generated code by compiling it

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 65da1fd has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 65da1fd with merge 65da1fd...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/svd2rust/builds/166243519)
Approved by: japaric
Pushing 65da1fd8a9f56fae0b4bbc8f2f7ada83c9f8b8b6 to master...

**Pull request merged**
