### PR TITLE
whole device generation

### LINKED ISSUE #40: [Feature] Support interrupt table generation
SVD files usually contain interrupts which can be used to generate interrupt vector table. 
Maybe support two modes:
- generate full table (both events and interrupts),
- generate only array with interrupts.

I'm not sure how it should look like, so this issue is just to fix absence of such feature. If I get some spare time, I'll try to experiment with it.

### LINKED ISSUE #60: Enum names collisions inside a register
Thanks @japaric for the amazing volume and quality of embedded work you're doing for the Rust community.

I'm working on [rust-lpc43xx](https://github.com/astro/rust-lpc43xx), and the [LPC43xx SVD](https://www.lpcware.com/content/nxpfile/lpc43sxx-svd-file) describes several fields in a register using the same \<enumeratedValues\> name, "ENUM". See for instance Timer0 peripheral's fields MR0I and MR0R. There are a dozen or so other examples for Timer0 alone, and a quick scan of the SVD indicates they use "ENUM" for *all* their \<enumeratedValues\> -- hundreds of examples.

I can think of a few ways to address this:

1. Name the enum struct using a concatenation of the field name and enumeratedValues name. This could result in longer names when referencing the enum, with the field name repeated in the enum struct name.
2. Find a way to scope the enum inside the field struct, or some other namespace. This seems a bit tidier, but not sure you can declare an enum inside a struct?
3. Ignore the enumeratedValues name altogether, if it's common practice for it to always be "ENUM", or if a field can only have one \<enumeratedValues\> block. I can't speak to whether those assumptions are true or not...

I think I understand the svd2rust code well enough that I could attempt to make any of the three changes outlined above. But I'm hoping somebody with a more informed opinion can speak up and help decide which is the best choice.

### PR DESCRIPTION
**Pull request by japaric**
Fixes #60
Closes #40

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 62a58d1 with merge 62a58d1...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/svd2rust/builds/210162426)

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit e508b52 with merge e508b52...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/svd2rust/build/1.0.43), [status-travis](https://travis-ci.org/japaric/svd2rust/builds/210163786)
State: approved= try=True

**Comment by japaric** [comment]
Will test a bit more and release cortex-m v0.2.0 before making a new release

**Pull request merged**
