### PR TITLE
add regression tests for #92 and #99

### LINKED ISSUE #92: "bits" is a valid field name
In that case the method to access the bitfield proxy:

``` rust
peripheral.register.read().bits() // BitsR
peripheral.register.read().bits().is_variant() // bool
```

is ambiguous with the register method to get its raw bits

``` rust
peripheral.register.read().bits()  // e.g. u8
```

This happens in the [SKEAZN84.svd](https://github.com/posborne/cmsis-svd/blob/python-0.4/data/Freescale/SKEAZN84.svd) file.

### PR DESCRIPTION
**Pull request by japaric**
closes #92

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 9ed581c has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 9ed581c with merge 9ed581c...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/svd2rust/build/1.0.101), [status-travis](https://travis-ci.org/japaric/svd2rust/builds/240102848?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 9ed581c99ca730a1d173b2fcd30f2b2d782e9754 to master...

**Pull request merged**
