### PR TITLE
make W.bits safe if WriteConstraint indicates so

### PR DESCRIPTION
**Pull request by japaric**
i.e. if WriteConstraint::Range covers the whole range of values that the
bitfield can take

This seems to work for the use case I had in mind

thoughts @cwoodall?

### CODE REVIEW

**Comment by cwoodall** [comment]
Yep! This isthe same as what I had written but not yet pushed! Works fine for me too!

**Comment by japaric** [comment]
@cwoodall Excellent.

@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 72c6782 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 72c6782 with merge 72c6782...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit a79f958 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit a79f958 with merge a79f958...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-appveyor](https://ci.appveyor.com/project/japaric/svd2rust/build/1.0.59)

**Comment by japaric** [comment]
@homunkulus retry

(network error)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:bangbang: Invalid head SHA found, retrying: `0000000000000000000000000000000000000000`

**Comment by homunkulus** [comment]
:pushpin: Commit a79f958 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit a79f958 with merge a79f958...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/svd2rust/build/1.0.60), [status-travis](https://travis-ci.org/japaric/svd2rust/builds/224912473)
Approved by: japaric
Pushing a79f95853e54b8597d867e4a07c887cef2521b7e to master...

**Pull request merged**
