### PR TITLE
add is_set / is_clear methods

### PR DESCRIPTION
**Pull request by japaric**
follow up of #84

cc @whitequark

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 3af4e87 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 3af4e87 with merge 3af4e87...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/svd2rust/build/1.0.74), [status-travis](https://travis-ci.org/japaric/svd2rust/builds/235323178?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 3af4e878701e650da19e0cabe177a0f87a0db03b to master...

**Pull request merged**
