### PR TITLE
extend test suite

### PR DESCRIPTION
**Pull request by japaric**
we now at least test one device per vendor in the SVD database

cc #45

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 90ffa4e has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 90ffa4e with merge 90ffa4e...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/svd2rust/builds/239454281?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 1ca0769 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 1ca0769 with merge 1ca0769...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 058330d has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 058330d with merge 058330d...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit f82b05d has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit f82b05d with merge f82b05d...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/svd2rust/builds/239458653?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 9d190f0 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 9d190f0 with merge 9d190f0...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/svd2rust/build/1.0.85), [status-travis](https://travis-ci.org/japaric/svd2rust/builds/239464001?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 9d190f05765adb4aa7e4f51c63a084c22501cdef to master...

**Pull request merged**
