### PR TITLE
[RFC] multiarch support for svd2rust

### PR DESCRIPTION
**Pull request by japaric**
# Background

@pftbest has been doing a great work at getting msp430 support at the
[cortex-m-quickstart] level by porting a bunch of cortex-m-* crates to msp430.
They also have a fork of svd2rust that can generate msp430 device crates from
msp430 SVD files.

[cortex-m-quickstart]: https://github.com/japaric/cortex-m-quickstart

In parallel @ahixon has been working with bare metal Cortex-A processors and
they also want to be able to use svd2rust to generate a device crate for their
Cortex-A processor.

This RFC / PR is about adding multiarch support to svd2rust to support these two
cases.

# How

As @ahixon suggested this RFC proposes moving non Cortex-M bits from the
`cortex-m` crate into a common crate: the [`mcu`] crate. Both the `cortex-m`
crate and the `msp430` crate, its MSP430 counterpart, will re-export the common
code from the `mcu` crate in their APIs. The shared API includes:

[`mcu`]: https://github.com/japaric/mcu

- the `Nr` trait
- the `Peripheral` struct
- the `CriticalSection` struct
- the `Mutex` struct

Additionally svd2rust will be tweaked to generate code that depends on the `mcu`
crate rather than on the `cortex-m` crate where possible.

Finally, a `--target` flag that accepts the values "cortex-m", "msp430" and
"none" will be added to the svd2rust tool. This flag tweaks code generation.
When "msp430" is selected the generated crate will depend on the `msp430` crate
and optionally (`#[cfg(feature = "rt")]`) on the `msp430-rt` crate. The
"cortex-m" value has a similar effect. The "none" flag forces the generated
crate to not depend on any specific architecture crate.

# Unresolved questions

- Is there a better name for the `mcu` crate?

- `--target` or `--arch`?

# Implementation bits

- [cortex-m](https://github.com/japaric/cortex-m/pull/57)
- svd2rust: this PR
- [msp430](https://github.com/pftbest/msp430/pull/1)
- [msp430-rt](https://github.com/pftbest/msp430-rt/pull/1)
- [msp430g2553](https://github.com/pftbest/msp430g2553/pull/1)
- [msp430-quickstart](https://github.com/japaric/msp430-quickstart), a demo

cc @awygle

### CODE REVIEW

**Comment by awygle** [comment]
I vote for `--target`. `--arch` would preclude us from having multiple targets which use the same MCU architecture, which I could see wanting in the future.

Without knowing a ton about the `mcu` crate, I wouldn't call a Cortex-A an MCU, so if you envision the A's using the crate I'd call it something else.

**Comment by pftbest** [comment]
Looks good! Agreed with @awygle on `--target` flag name.

Don't know a better name for mcu. Maybe I would have named it as `mcu_common` or `mcu_support` to denote that it's not very useful as standalone crate, but is just a part of a bigger ecosystem.

P.S.
I see that you pulled the changes back into cortex-m* crates, what do you think, would it be better to keep both targets in a single repo since they have so much in common? or you just did it for testing purposes because I didn't update them yet for the new interrupt mechanics?

**Comment by brson** [comment]
Oh, man so much good stuff happening. Thanks @pftbest and @ahixon.

**Comment by japaric** [comment]
Alright let's go ahead with `--target` instead of `--arch`.

As for renaming `mcu`, how does `embedded-common` sound? I originally wanted to name that crate `embedded` but the name is already taken on crates.io.

@ahixon, I would love to hear if the changes in this PR are enough for your use case.

**Comment by ahixon** [comment]
Hah, good timing! I only just got back from a short holiday and am going through my Github notifications now.

Another +1 for `--target`.

Also agree with the `mcu` name not fully encompassing the crate's purpose. `embedded-common` sounds good, though!

Otherwise, yeah, this looks great! :)

**Comment by awygle** [comment]
`embedded-common` is definitely better, but it feels a little bit vague ("embedded" doesn't really mean anything - is a Cortex-A5 embedded? What about an A-53?). Again, stressing that I haven't really dug into what the proposed crate would include (I've been stupid-busy - thanks @pftbest for continuing great work!), maybe the names `baremetal` or `baremetal-common` are a better fit?

**Comment by japaric** [comment]
I have gone with bare-metal for the name. The crate is now [on crates.io](https://crates.io/crates/bare-metal)

Thanks everyone for the input. Let's land this.

@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit ffcc983 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit ffcc983 with merge ffcc983...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit c7aed0a has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit c7aed0a with merge c7aed0a...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/svd2rust/build/1.0.106), [status-travis](https://travis-ci.org/japaric/svd2rust/builds/250940503?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing c7aed0ac33a148ad17243dd55447e6b9ee3de2e1 to master...

**Pull request merged**
