### PR TITLE
disable incremental compilation

### PR DESCRIPTION
**Pull request by japaric**
this should hopefully fix the timeout reported in #166

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 65082ee has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 65082ee42bc4efd7c2d8427400dcd3eab2e9d2c1 with merge 7254cea42da41f1a05235a3076a6e94d1577f437...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/svd2rust/builds/329237205?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
> this should hopefully fix the timeout reported in #166

Nope. It still times out. Perhaps compilation speed regressed in general for some other reason. We'll have to reduce the size of this test group or split it in half.

**Pull request closed without merging**
