### PR TITLE
make the re-exported core peripheral types uppercase as well

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 20c2e20 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 20c2e20 with merge 20c2e20...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/svd2rust/build/1.0.98), [status-travis](https://travis-ci.org/japaric/svd2rust/builds/239806473?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 20c2e2073744f3609eb870bafd814f204d04c997 to master...

**Pull request merged**
