### PR TITLE
fix clippy warnings

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit c2a3676 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit c2a3676 with merge c2a3676...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/svd2rust/builds/167413612)
Approved by: japaric
Pushing c2a3676bd0bf047d536b3d77e7e9b276192bf965 to master...

**Pull request merged**
