### PR TITLE
Add support for building the e310x crate

### PR DESCRIPTION
**Pull request by dvc94ch**

### CODE REVIEW

**Comment by jamesmunns** [comment]
Hey @dvc94ch, it looks generally good to me, would you mind adding some good RISC-V examples (or at least the e310x svd) to the regression tests? Check out `/ci/script.sh` (and let me know if you need help). This way we can make sure we don't accidentally break support when changing something else.

Once you do that, I can trigger CI and LGTM.

**Comment by dvc94ch** [comment]
@jamesmunns Thank you for the quick review! I won't get around to it till tomorrow.

**Comment by jamesmunns** [comment]
Thanks! Lets see how CI goes.

bors r+

**Comment by dvc94ch** [comment]
I'm getting permission denied when I click the red cross [0], can you post a log?

[0] https://app.bors.tech/repositories/1953/log#batch-4578

**Comment by japaric** [comment]
All tests passed so merging manually.

I'll increase the timeout from 1 hour to 2.

**Pull request merged**
