### PR TITLE
add interrupt number to the interrupts' documentation

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit e566814 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit e566814 with merge e566814...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/svd2rust/build/1.0.48), [status-travis](https://travis-ci.org/japaric/svd2rust/builds/210297529)
Approved by: japaric
Pushing e5668140b1d202f2d6fd7e57df118a5bd93ecb73 to master...

**Pull request merged**
