### PR TITLE
don't generate an API for core peripherals

### PR DESCRIPTION
**Pull request by japaric**
instead re-export the cortex-m crate's API

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 1c6e72f has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 1c6e72f with merge 1c6e72f...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/svd2rust/build/1.0.62), [status-travis](https://travis-ci.org/japaric/svd2rust/builds/225771961)
Approved by: japaric
Pushing 1c6e72f7143ede72d7f6355e1fb86421df523b1c to master...

**Pull request merged**
