### PR TITLE
change the fields of interrupt::Handlers to pascal case

### PR DESCRIPTION
**Pull request by japaric**
see commit messages for the rationale

this is a breaking change

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit e8afc8e has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit e8afc8e with merge e8afc8e...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/svd2rust/build/1.0.54), [status-travis](https://travis-ci.org/japaric/svd2rust/builds/221197933)
Approved by: japaric
Pushing e8afc8e37944e345877e299b78f58b839fc284c2 to master...

**Pull request merged**
